### PR TITLE
Drop global variables in CLI

### LINKED ISSUE #133: jvsctl requires a server for breakglass
### TL;DR

The `jvsctl` command requires a `server` property, even for breakglass tokens.

### Expected behavior

Breakglass should not require a server.

### Observed behavior

Breakglass requires a server.

### Environment Details

```markdown
Everywhere
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sethvargo**
This removes the use of global variables for state in pkg/cli, which has the added benefit of allowing CLI tests to run in parallel. This new pattern ensures configuration is loaded and passed to child commands.

Fixes #133

### CODE REVIEW

File: pkg/config/cli_config.go [hunk 1]
```diff
@@ -30,13 +30,8 @@ type CLIConfig struct {
 	// Server is the JVS server address.
 	Server string `yaml:"server,omitempty"`
 
-	// Authentication is the authentication config.
```
Comment (sethvargo) [inline pkg/config/cli_config.go:33]: ⚠️ This is a change. I don't know why this was an embedded struct.

File: pkg/config/cli_config.go [hunk 2]
```diff
@@ -51,10 +46,6 @@ func (cfg *CLIConfig) Validate() error {
 			cfg.Version, CLIConfigVersions.List()))
 	}
 
-	if cfg.Server == "" {
```
Comment (sethvargo) [inline pkg/config/cli_config.go:54]: This validation makes it so we cannot generate breakglass tokens.

File: pkg/cli/root.go [hunk 3]
```diff
@@ -12,89 +12,83 @@
...
+	vpr.SetConfigType("yaml")
+	vpr.SetEnvPrefix("JVSCTL")
+	vpr.AutomaticEnv()
+	vpr.SetConfigFile(pth)
+
+	if err := vpr.ReadInConfig(); err != nil {
+		// Don't throw an error for failing to find the default config path since
+		// it's not required. However, if the user specified a config path that
+		// doesn't exist, that's an error.
+		if !errors.Is(err, &viper.ConfigFileNotFoundError{}) && !errors.Is(err, os.ErrNotExist) {
```
Comment (yolocs) [inline pkg/cli/root.go:78]: I thought viper returns ConfigFileNotFoundError if os.ErrNotExist. Are you doing this for safety?

File: pkg/cli/root.go [hunk 4]
```diff
@@ -12,89 +12,83 @@
...
+			return fmt.Errorf("failed to read configuration file: %w", err)
+		}
+		if pth != defaultConfigPath {
+			return fmt.Errorf("failed to read configuration file: %w", err)
+		}
```
Comment (yolocs) [inline pkg/cli/root.go:83]: 👍

File: pkg/cli/root_test.go [hunk 5]
```diff
@@ -15,36 +15,127 @@
...
+// testExecteCommand executes the given cobra command and returns the stdout,
+// stderr, and any execution error. See [testExecuteCommandStdin] for more
+// information.
+func testExecuteCommand(tb testing.TB, cmd *cobra.Command, args ...string) (string, string, error) {
+	tb.Helper()
+	return testExecuteCommandStdin(tb, cmd, nil, args...)
+}
+
+// testExecuteCommandStdin executes the given cobra command with the stdin
+// writer w and returns the stdout, stderr, and any errors that occur during
```
Comment (yolocs) [inline pkg/cli/root_test.go:123]: "stdin reader"?

File: pkg/cli/token.go [hunk 6]
```diff
@@ -19,64 +19,101 @@ import (
...
 	"github.com/abcxyz/jvs/pkg/idtoken"
 	"github.com/abcxyz/jvs/pkg/justification"
 )
 
-const (
-	Issuer  = "jvsctl"
-	Subject = "jvsctl"
-)
+// tokenCmdOptions holds all the inputs and flags for the token subcommand.
+type tokenCmdOptions struct {
```
Comment (yolocs) [inline pkg/cli/token.go:41]: This is a good pattern to codify.

File: pkg/cli/token_test.go [hunk 7]
```diff
@@ -15,190 +15,176 @@
...
+	b, err := jwt.Sign(token, jwt.WithKey(jwa.HS256, []byte("testing")))
 	if err != nil {
-		t.Fatal(err)
-	}
-	expectedJustifications := []*jvspb.Justification{
-		{
-			Category: "breakglass",
-			Value:    "i-have-reason",
-		},
+		return nil, fmt.Errorf("failed to sign breakglass token: %w", err)
```
Comment (yolocs) [inline pkg/cli/token_test.go:184]: Copy/paste error? 
```suggestion
		return nil, fmt.Errorf("failed to sign token: %w", err)
```

File: pkg/cli/token_test.go [hunk 8]
```diff
@@ -15,190 +15,176 @@
...
-		t.Errorf("expected length %d to be %d: %#v", len(sigs), want, sigs)
-	} else {
-		headers := sigs[0].ProtectedHeaders()
-		if got, want := headers.Type(), "JWT"; got != want {
-			t.Errorf("typ: expected %q to be %q", got, want)
-		}
-		if got, want := string(headers.Algorithm()), "HS256"; got != want {
-			t.Errorf("alg: expected %q to be %q", got, want)
-		}
+func (j *fakeJVS) CreateJustification(_ context.Context, req *jvspb.CreateJustificationRequest) (*jvspb.CreateJustificationResponse, error) {
```
Comment (yolocs) [inline pkg/cli/token_test.go:159]: This is beyond my bar :) Since we're returning whatever token the server returns as a string, I would not really generate a real JTW.

File: pkg/config/cli_config.go (hunk 2 above)
Comment (yolocs) [reply pkg/config/cli_config.go:54]: Ack

File: pkg/config/cli_config.go (hunk 1 above)
Comment (yolocs) [reply pkg/config/cli_config.go:33]: I'm not a fan of a flat config and I was projecting a more complicated authentication config. We're using the application default credential to generate id token. Cloud Run accepts that. But not with IAP (we can forget about it now) or other authentication middleware (what if it requires an access token instead of id token). That's why I had the sub-struct. I could be overthinking.

**Review by yolocs — APPROVED** [review]

File: pkg/cli/root.go (hunk 3 above)
Comment (sethvargo) [reply pkg/cli/root.go:78]: Nope. I found it returns `ConfigFileNotFoundError` when given a _file_ path that does not exist, but returns `ErrNotExist` when given a _directory_ path that does not exist. `ConfigFileNotFoundError` only seemed to throw when the file had an extension.

File: pkg/cli/root_test.go (hunk 5 above)
Comment (sethvargo) [reply pkg/cli/root_test.go:123]: Updated.

File: pkg/cli/token_test.go (hunk 7 above)
Comment (sethvargo) [reply pkg/cli/token_test.go:184]: You caught me 😄

File: pkg/cli/token_test.go (hunk 8 above)
Comment (sethvargo) [reply pkg/cli/token_test.go:159]: The reason I did this is so we can use the same table-driven tests for testing breakglass tokens and testing tokens. Otherwise the testing logic becomes branching and that's less than ideal.

File: pkg/config/cli_config.go (hunk 1 above)
Comment (sethvargo) [reply pkg/config/cli_config.go:33]: The reason I went with the flag config is because it's trivial to accidentally NPE if we're not careful. 

```go
var cfg config.CLIConfig

// later

if cfg.Authentication.Insecure { // npe
}
```

Since neither `Validate` nor `SetDefault` build the deeply-nested struct, it feels risky.

Comment (yolocs) [reply pkg/config/cli_config.go:33]: It was initialized in SetDefault. But I think it's probably better to keep it simple now.

**Review by yolocs — APPROVED** [review]
