### PR TITLE
fix: use primary key version instead of latest key version to sign the token

### LINKED ISSUE #106: Sign token with primary instead of latest version
### TL;DR

Sign token with primary instead of latest version
https://github.com/abcxyz/jvs/blob/23cdda185a8fc277ba798bfaf3e34543458f1934/pkg/justification/processor.go#L100

### Expected behavior

_No response_

### Observed behavior

_No response_

### Environment Details

```markdown
None
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by capri-xiyue**
fix #106 
1. use primary key version instead of latest key version to sign the token 
2. fix main brnach lint error(ran into multiple lint errors from main branch)

### CODE REVIEW

File: test/integ/main_test.go [hunk 1]
```diff
@@ -244,6 +245,7 @@ func TestJVS(t *testing.T) {
 	}
 }
 
+//nolint:tparallel // subtests need to run in sequence.
```
Comment (sethvargo) [inline test/integ/main_test.go:248]: Can you elaborate on why?

File: test/integ/main_test.go [hunk 2]
```diff
@@ -736,12 +742,14 @@ func testIsIntegration(tb testing.TB) bool {
...
 // Create an asymmetric signing key for use with integration tests.
-func testCreateKey(ctx context.Context, tb testing.TB, kmsClient *kms.KeyManagementClient, keyRing string) string {
+func testCreateKey(ctx context.Context, tb testing.TB, kmsClient *kms.KeyManagementClient, keyRing, primaryKeyVersion string) string {
 	tb.Helper()
 	u, err := uuid.NewUUID()
 	if err != nil {
 		tb.Fatalf("failed to create uuid : %s", err)
 	}
+	labels := make(map[string]string)
+	labels["primary"] = "ver_" + primaryKeyVersion
```
Comment (sethvargo) [inline test/integ/main_test.go:752]: 1. It would be better to just make the map: `labels := map[string]string{"primary": "ver_"+primaryKeyVersion}`

2. Why do we need to store the primary version on a label? There's already a `primary` field on the proto which links to the specific version: https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys#CryptoKey

File: test/integ/main_test.go (hunk 1 above)
Comment (capri-xiyue) [reply test/integ/main_test.go:248]: It was written in https://github.com/abcxyz/jvs/blob/23cdda185a8fc277ba798bfaf3e34543458f1934/test/integ/main_test.go#L280
Should I move the original comment to here to make it clear?

File: test/integ/main_test.go (hunk 2 above)
Comment (capri-xiyue) [reply test/integ/main_test.go:752]: Why do we need to store the primary version on a label? 
JVS use labels to store the primary version https://github.com/abcxyz/jvs/blob/23cdda185a8fc277ba798bfaf3e34543458f1934/pkg/jvscrypto/kmsutil.go#L198 instead of the `primary` field. Do we want to change it to the `primary` field now?

File: test/integ/main_test.go (hunk 1 above)
Comment (sethvargo) [reply test/integ/main_test.go:248]: Yes, please

File: test/integ/main_test.go (hunk 2 above)
Comment (yolocs) [reply test/integ/main_test.go:752]: We should definitely use the `primary` field in the KMS API. I'm surprised we didn't discover that in the first place.

Comment (sethvargo) [reply test/integ/main_test.go:752]: @raserva do you remember why we used labels to store the primary version instead of the `primary` proto field?

It would be better to use the `primary` field directly, since fetching the `cryptoKey` will then return the embedded `cyrptoKeyVersion` directly in the same API call. There's a separate API method for setting the primary version: https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys/updatePrimaryVersion

Comment (raserva) [reply test/integ/main_test.go:752]: primary isn't supported for async keys.

Comment (raserva) [reply test/integ/main_test.go:752]: https://cloud.google.com/kms/docs/key-states#symmetric_encryption

Comment (raserva) [reply test/integ/main_test.go:752]: Trying to find where that is explicitly stated, but i did try to use that field.

Comment (raserva) [reply test/integ/main_test.go:752]: This is called out in [the original PR](https://github.com/abcxyz/jvs/pull/25). 

> Unfortunately, there is no standard way in KMS to mark an asymmetric key as primary (there is a primary field, but it is unsupported for asymettric keys). Therefore, we need to store this information somewhere else. This solves this issue by utilizing [KMS key labels](https://cloud.google.com/kms/docs/creating-managing-labels) primary, new, old. This allows us to distinguish between new key versions and handle odd cases gracefully, such as rollbacks.

Comment (raserva) [reply test/integ/main_test.go:752]: Here you go. 
```
rsrv@rsrv-desktop:~$ gcloud kms keys set-primary-version <mykey> --version=1 --location=global --keyring=ci-keyring
ERROR: (gcloud.kms.keys.set-primary-version) FAILED_PRECONDITION: Keys with purpose ASYMMETRIC_SIGN do not have a primary version.
- '@type': type.googleapis.com/google.rpc.PreconditionFailure
  violations:
  - subject: <mykey>
    type: CRYPTO_SCHEME_MISMATCH
- '@type': type.googleapis.com/google.rpc.DebugInfo
  detail: '[ORIGINAL ERROR] generic::failed_precondition: Keys with purpose ASYMMETRIC_SIGN
    do not have a primary version. [google.rpc.error_details_ext] { message: "Keys
    with purpose ASYMMETRIC_SIGN do not have a primary version." details { [type.googleapis.com/google.rpc.PreconditionFailure]
    { violations { type: "CRYPTO_SCHEME_MISMATCH" subject: "<mykey>"
    } } } }'
```

Comment (capri-xiyue) [reply test/integ/main_test.go:752]: I found docs here: https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys
`Keys with [purpose](https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys#CryptoKey.FIELDS.purpose) [ENCRYPT_DECRYPT](https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys#CryptoKeyPurpose.ENUM_VALUES.ENCRYPT_DECRYPT) may have a primary. For other keys, this field will be omitted.`

Comment (capri-xiyue) [reply test/integ/main_test.go:752]: I will add a comment in setting primary method to explicitly list the reason why we don't use the `primary` field.

Comment (sethvargo) [reply test/integ/main_test.go:752]: Let's document that rationale inline 😄

File: test/integ/main_test.go (hunk 1 above)
Comment (capri-xiyue) [reply test/integ/main_test.go:248]: done

File: pkg/jvscrypto/kmsutil.go [hunk 3]
```diff
@@ -180,21 +180,23 @@ func SignToken(token *jwt.Token, signer crypto.Signer) (string, error) {
...
+	if primary, ok := response.Labels[PrimaryKey]; ok {
+		primary = strings.TrimPrefix(primary, PrimaryLabelPrefix)
 		return fmt.Sprintf("%s/cryptoKeyVersions/%s", key, primary), nil
 	}
 	// no primary found
 	return "", nil
 }
 
 // SetPrimary sets the key version name as primary in the key labels.
+// 'Primary' field will be omitted for keys with purpose other than ENCRYPT_DECRYPT(https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys).
```
Comment (yolocs) [inline pkg/jvscrypto/kmsutil.go:198]: nit: also mention what's the key type we're using.

File: pkg/justification/processor_test.go [hunk 4]
```diff
@@ -188,6 +103,95 @@ func TestCreateToken(t *testing.T) {
 	for _, tc := range tests {
 		tc := tc
 		t.Run(tc.name, func(t *testing.T) {
+			t.Parallel()
+			var clientOpt option.ClientOption
+			key := "projects/[PROJECT]/locations/[LOCATION]/keyRings/[KEY_RING]/cryptoKeys/[CRYPTO_KEY]"
+			version := key + "/cryptoKeyVersions/[VERSION]"
+			keyID := key + "/cryptoKeyVersions/[VERSION]-0"
+			mockKeyManagement := &testutil.MockKeyManagementServer{
```
Comment (yolocs) [inline pkg/justification/processor_test.go:111]: Great we can make it parallel!

Could you do a refactor to make use of https://github.com/abcxyz/pkg/blob/main/testutil/grpc.go?

**Review by yolocs — COMMENTED** [review]
All other looks good to me

File: pkg/jvscrypto/kmsutil.go (hunk 3 above)
Comment (capri-xiyue) [reply pkg/jvscrypto/kmsutil.go:198]: DONE

**Review by yolocs — APPROVED** [review]
